version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.16

  pre_build:
    commands:
      - go mod download

  build:
    commands:
      - go vet $(go list ./... | grep -v /vendor/)
      - go build $(go list ./... | grep -v /vendor/)
      - go test -v $(go list ./... | grep -v /vendor/)