version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.1x

  pre_build:
    commands:
      - go mod download

  build:
    commands:
      - go vet $(go list ./... | grep -v /vendor/)
      - go test $(go list ./... | grep -v /vendor/)